### ISSUE TITLE
Error regenerating docker file

### ISSUE THREAD

**Issue by stv8** [fly-apps/dockerfile-rails#141]
```
.gem/ruby/3.3.5/gems/dockerfile-rails-1.7.3/lib/generators/dockerfile_generator.rb:1618:in `+': no implicit conversion of nil into String (TypeError)

        subsection + spaces + %(url: <%= URI.parse(ENV["DATABASE_URL"]).tap { |url| url.path += "_#{name}" } if ENV["DATABASE_URL"] %>\n)
```

I'm on rails 8 and this is my db config for prod

```
production:
  # we use DATABASE_URL secret stored in Fly.io
  primary:
    <<: *default
    database: my_db
  cache:
    adapter: sqlite3
    database: storage/production_cache.sqlite3
    migrations_paths: db/cache_migrate
  queue:
    adapter: sqlite3
    database: storage/production_queue.sqlite3
    migrations_paths: db/queue_migrate
  cable:
    adapter: sqlite3
    database: storage/production_cable.sqlite3
    migrations_paths: db/cable_migrate
```
