### ISSUE TITLE
Support secrets for a private gemserver

### ISSUE THREAD

**Issue by tmaier** [fly-apps/dockerfile-rails#40]
I host some gems in a private gemserver.

As it seems, dockerfile-rails does not support to set secrets.

This is how I do it in my current `Dockerfile`:

```ruby
RUN --mount=type=secret,id=gemserver_credentials,dst=/kaniko/gemserver_credentials \
  --mount=type=cache,id=gems,sharing=locked,target=/app/vendor/cache \
  BUNDLE_GEMS__MYSERVER__COM="$(cat /kaniko/gemserver_credentials)" \
  && mkdir -p /usr/local/bundle \
  && export BUNDLE_GEMS__MYSERVER__COM \
  && bundle config set cache_all true \
  && bundle install \
  && find /usr/local/bundle/ -name ".git" -exec rm -rv {} + \
  && find /usr/local/bundle/ -name "*.c" -delete \
  && find /usr/local/bundle/ -name "*.o" -delete \
  && bundle cache \
  && bundle config unset cache_all \
  && rm -rf /usr/local/bundle/ruby/*/cache
```

Notable is

- I use env variables, as to pass the credentials to bundler
- `--mount=type=secret,id=gemserver_credentials,dst=/kaniko/gemserver_credentials` I mount the secret at `/kaniko` to be able to support kaniko next to docker build
- `BUNDLE_GEMS__MYSERVER__COM="$(cat /kaniko/gemserver_credentials)"` reads the secret
- `export BUNDLE_GEMS__MYSERVER__COM ` exposes the secret to bundler

I also have a special Docker Compose file, which I load in addition to the normal docker-compose.yml file

```yml
version: '3.8'

services:
  web:
    build:
      secrets:
        - gemserver_credentials
    secrets:
      - gemserver_credentials

secrets:
  gemserver_credentials:
    file: ./BUNDLE_GEMS__MYSERVER__COM.txt
```
