### ISSUE TITLE
Install Bun when it is being used instead of Node

### ISSUE THREAD

**Issue by luizkowalski** [fly-apps/dockerfile-rails#60]
The latest jsbundling-rails release includes the ability to use [bun](https://bun.sh/) as well. It would be nice if when the Dockerfile is being generated, it could also detect `bun` as the js runtime (probably via the presence of `bun.lockb` or `bun.config.js` files and use that instead of Node

**Comment by rubys** [comment]
Where bun was added https://github.com/rails/jsbundling-rails/pull/167

**Comment by rubys** [comment]
Initial support installs bun instead of yarn.  Node in still installed, for now.  I should be able to remove Node.  Neither node nor bun will be in the deployed image unless execjs is used.

**Comment by rubys** [comment]
reopening as testing without node at all is going surprisingly well...

**Comment by luizkowalski** [comment]
hey Sam!
first of all, thank you so much for the quick reply and implementation!

I'm still getting mentions of `yarn.lock` on my Dockerfile

This is my configuration:
```
# generated by dockerfile-rails

---
options:
  bin-cd: true
  cache: true
  fullstaq: true
  jemalloc: true
  parallel: true
  postgresql: true
  redis: true
  root: true
  yjit: true
  envs:
    base:
      BUNDLE_WITHOUT: development:test:linting:profiler
      GIT_REV: "${GIT_REV}"
      BUILD_DATE: "${BUILD_DATE}"
  args:
    base:
      GIT_REV: "${GIT_REV}"
      BUILD_DATE: "${BUILD_DATE}"

```

and this is what is being generated (relevant part)

```dockerfile
# Throw-away build stages to reduce size of final image
FROM base as prebuild

# Install packages needed to build gems and node modules
RUN --mount=type=cache,id=dev-apt-cache,sharing=locked,target=/var/cache/apt \
    --mount=type=cache,id=dev-apt-lib,sharing=locked,target=/var/lib/apt \
    apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential curl libpq-dev node-gyp pkg-config python-is-python3


FROM prebuild as node

# Install Node.js
ARG NODE_VERSION=20.6.1
ARG BUN_VERSION=1.0.0
ENV PATH=/usr/local/node/bin:$PATH
RUN curl -sL https://github.com/nodenv/node-build/archive/master.tar.gz | tar xz -C /tmp/ && \
    /tmp/node-build-master/bin/node-build "${NODE_VERSION}" /usr/local/node && \
    npm install -g bun@$BUN_VERSION && \
    rm -rf /tmp/node-build-master

# Install node modules
COPY --link package.json yarn.lock ./
RUN --mount=type=cache,id=bld-yarn-cache,target=/root/.yarn \
    YARN_CACHE_FOLDER=/root/.yarn bun install --frozen-lockfile

```
