### ISSUE TITLE
`packages` directive on `dockerfile.yaml` doesn't install all packages

### ISSUE THREAD

**Issue by luizkowalski** [fly-apps/dockerfile-rails#63]
I have a config file like this:

```
# generated by dockerfile-rails

---
options:
  bin-cd: true
  cache: true
  fullstaq: true
  jemalloc: true
  parallel: true
  postgresql: true
  redis: true
  root: true
  yjit: true
  packages:
    base:
    - git
    - libyaml-dev
  envs:
    base:
      BUNDLE_WITHOUT: development:test:linting:profiler
      GIT_REV: "${GIT_REV}"
      BUILD_DATE: "${BUILD_DATE}"
      RAILS_LOG_TO_STDOUT: 'true'
  args:
    base:
      GIT_REV: "${GIT_REV}"
      BUILD_DATE: "${BUILD_DATE}"

```

when I try to generate the Dockerfile, `libyaml-dev` is simply ignored, no matter what I try and if I manually add it to the Dockerfile, it gets wiped if I try to regenerate the Dockerfile.

I'm not sure if it is related or not but I'm using Rails from the main branch and when I run the generator, I see this before anything else:

```
The git source https://github.com/rails/rails.git is not yet checked out. Please run `bundle install` before trying to start your application
   identical  Dockerfile
   identical  .dockerignore
   identical  .node-version
   identical  bin/docker-entrypoint
   identical  config/dockerfile.yml
```

even though the git source is definitely checked out
